### ISSUE TITLE
log stash continually restarting

### ISSUE THREAD

**Issue by mklatsky** [willdurand/docker-elk#10]
When running the elk container, I see a continuous stream of the following:

elk_1 | 2015-05-20 19:45:05,570 INFO spawned: 'logstash' with pid 140
elk_1 | 2015-05-20 19:45:06,572 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1 | 2015-05-20 19:45:17,404 INFO exited: logstash (exit status 1; not expected)
elk_1 | 2015-05-20 19:45:18,409 INFO spawned: 'logstash' with pid 172

Its seems that continuously restarts. I am not quite sure of the cause, and the logs are not tremendously informative so far.

**Comment by willdurand** [comment]
That might happen if Logstash cannot find any configuration file. Do you have one?

**Comment by mklatsky** [comment]
I have this mapped (this is from my docker-compose.yml file):

volumes:
    - /opt/docker/logstash/config:/etc/logstash

and then:

#ls -la  /opt/docker/logstash/config
logstash.conf

This just consists of:

input {
  lumberjack {
    port => 5043
    ssl_certificate => "/etc/ssl/logstash-forwarder.crt"
    ssl_key => "/etc/ssl/logstash-forwarder.key"
  }
}

filter {
  if [type] == "hipache" {
    grok {
      patterns_dir => "/etc/logstash/patterns/nginx"
      match => { "message" => "%{NGINXACCESS}" }
    }
  }
}

output {
  elasticsearch {
    host => "127.0.0.1"
    cluster => "logstash"
    # Uncomment the line below if you use Kibana 3.1.0
    # embedded => false
  }
}

**Comment by mklatsky** [comment]
I found the issue- it was simpler than I expected. I pasted an incorrect logstash.conf file. The file I had actually included the following line:

host => 10.5.5.0

log stash really wanted quotes around the IP address, so this was simply a log stash config file syntax error. Thank you for pointing me in the right direction.

**Comment by willdurand** [comment]
ah cool :-) that's a bit sad that Logstash does not give better hints about the issue..

**Comment by cedvan** [comment]
Maybe add default config file ?

**Comment by nicgirault** [comment]
yes a default config file would have been appreciated! Thank you @willdurand for this docker!
