### ISSUE TITLE
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out

### ISSUE THREAD

**Issue by rsignavong** [willdurand/docker-elk#12]
Hi,

I've got the following error when running 'docker build .' on Step 5.

Step 5 : RUN apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 &&     if ! grep "elasticsearch" /etc/apt/sources.list; then echo "deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main" >> /etc/apt/sources.list;fi &&     if ! grep "logstash" /etc/apt/sources.list; then echo "deb http://packages.elasticsearch.org/logstash/1.4/debian stable main" >> /etc/apt/sources.list;fi &&     apt-get update
 ---> Running in 5a6cff0bfe61
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.eNDWVDUFrg --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4
gpg: requesting key D88E42B4 from hkp server pool.sks-keyservers.net
?: pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 &&     if ! grep "elasticsearch" /etc/apt/sources.list; then echo "deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main" >> /etc/apt/sources.list;fi &&     if ! grep "logstash" /etc/apt/sources.list; then echo "deb http://packages.elasticsearch.org/logstash/1.4/debian stable main" >> /etc/apt/sources.list;fi &&     apt-get update' returned a non-zero code: 2

And then the build stop... What should I do?

Your help will grandly appreciated.

Regards,

Rocky

**Comment by willdurand** [comment]
This is weird.. Any restriction on your Internet connection maybe? Could you please retry to build the image?

PS: I've compiled a small demo project featuring this image: https://github.com/willdurand/gitlab-elk-demo.

**Comment by willdurand** [comment]
Looks like you have to retry to build the image until it works. Happened to me on Docker Hub today...

**Comment by rsignavong** [comment]
Okay, thank you for your reply.

We have finally installed Elastic and Kibana on our own AWS EC2 instance
instead of using Docker for our use case.

2015-08-25 17:31 GMT+02:00 William Durand <notifications@github.com>:

> Looks like you have to retry to build the image until it works. Happened
> to me on Docker Hub today...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/willdurand/docker-elk/issues/12#issuecomment-134628162>
> .
>



-- 
Rocky SIGNAVONG
