### ISSUE TITLE
"Real use case" description pretty confusing: when providing your own logstash.conf, do you have to redefine output section?

### ISSUE THREAD

**Issue by dborzov** [willdurand/docker-elk#13]
> Your logstash configuration SHOULD contain the following input definition:

Does the provided config version complement the default one? Or do you have to include the `output` section in my custom `logstash.conf` as well:
```
output {
  elasticsearch {
    host => elasticsearch
  }
}
```

More generally, it would have been helpful if the README.md provided complete instructions to one complete example of this container being used.

**Comment by willdurand** [comment]
Hi @dborzov, and first, sorry for the delay!

I've open sourced a demo project that should (hopefully) help you: https://github.com/willdurand/gitlab-elk-demo.
