### ISSUE TITLE
large startup time

### ISSUE THREAD

**Issue by bergtwvd** [willdurand/docker-elk#24]
When I start the container I notice the log messages of the processes being started in the elk container. However they seem to take a while to actually start processing. E.g. logstash misses many of the initial log messsages produced by other containers. The Kibana site is also available only after some time. Is there some initialization processing going on before data can be processed?

**Comment by hacfi** [comment]
Elasticsearch (Java) can take a couple of seconds to get up and running. If it’s more than that something could be wrong. I’m not sure about Kibana.

**Comment by willdurand** [comment]
As @hacfi said, it takes some time to get ES running correctly. Same thing for Kibana, which waits for ES. I think it takes up to 15s to get everything working, but there is nothing I can do for that.

Or maybe we could use [Docker 1.12 healthcheck feature](https://fabioit.wordpress.com/2016/08/30/docker-1-12-health-check/).
