### ISSUE TITLE
Logstash does not find the conf file

### ISSUE THREAD

**Issue by gjdass** [willdurand/docker-elk#26]
Hi.

First, thanks for this github repo. It's really cool to be able to get started quickly with all that stuff without making some complicated networks and multiple containers with docker.

I have some troubles tho. I pulled `5.X` docker images, and logstash refuses to start due to the config file he can't find (whereas the conf file is here in `/etc/logstash`) :

```shell
WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
Could not find log4j2 configuration at path /etc/logstash/log4j2.properties. Using default config which logs to console
ERROR: No configuration file was specified. Perhaps you forgot to provide the '-f yourlogstash.conf' flag?
usage:
  bin/logstash -f CONFIG_PATH [-t] [-r] [] [-w COUNT] [-l LOG]
  bin/logstash -e CONFIG_STR [-t] [--log.level fatal|error|warn|info|debug|trace] [-w COUNT] [-l LOG]
  bin/logstash -i SHELL [--log.level fatal|error|warn|info|debug|trace]
  bin/logstash -V [--log.level fatal|error|warn|info|debug|trace]
  bin/logstash --help
2017-05-07 00:32:19,592 INFO exited: logstash (exit status 1; not expected)
```

My command line :
```shell
docker run --name elk -d -p 4242:80 -v E:/docker/logstash:/etc/logstash willdurand/elk:kibana-5.x
```

The config file :
```text
input {
  lumberjack {
    port => 5043
  }
}
output {
  elasticsearch {
    host => "127.0.0.1"
    cluster => "logstash"
    embedded => false
  }
}
```

I can see the config file by making a `ls /etc/logstash` into the container. Even a `chmod 777` on the file did not change anything. Still no way to make logstash working. It's like he can't see the file while I'm seeing it on the console (attached to the container as root).

Am I missing something ? Sorry for the inconvenience if this is the case, but I really can't find why anywhere.

Thanks.

**Comment by willdurand** [comment]
This is something I need to investigate because I don't think you made a mistake..

**Comment by joris-lambrechts** [comment]
I had the same issue using the official docker image from elastic. Turned out my custom mounted `logstash.yml` didn't contain `path.config: /usr/share/logstash/pipeline`

**Comment by willdurand** [comment]
@gjdass could you maybe confirm what @joris-lambrechts has indicated?

**Comment by gjdass** [comment]
@willdurand I'll look into it as soon as I got some time ;) Will post an update here.

**Comment by dcorrea777** [comment]
I have the same problem.

I'm using the official elastic image docker.

**Comment by dcorrea777** [comment]
Sorry, now that I've seen it's a personal project, hahaha.

But if you can afford it, I'm very grateful.

**Comment by dcorrea777** [comment]
@gjdass and @joris-lambrechts I solved this problem by adding configuration in my logstash.yml file
`path.config: /usr/share/logstash/pipeline`

**Comment by willdurand** [comment]
> Sorry, now that I've seen it's a personal project, hahaha.
> 
> But if you can afford it, I'm very grateful.

Heh. What do you mean?

**Comment by dcorrea777** [comment]
> Heh. What do you mean?

I thought it was in elastic github, after I saw it was a project of yours. But the problem was the same, but it was solved.

**Comment by willdurand** [comment]
ah ok cool. I did read your comments a bit too fast and did not completely understood the situation. Thanks!
