### ISSUE TITLE
Cannot initialize Kibana

### ISSUE THREAD

**Issue by cooniur** [willdurand/docker-elk#6]
I stuck at the first step of configuring Kibana, which is `Configure an index pattern`.

I checked the two boxes `Index contains time-based events` and `Use event times to create index names`. I used the default index name or pattern `[logstash-]YYYY.MM.DD`. But Kibana says `Unable to fetch mapping. Do you have indices matching the pattern?`.

I'm not able to continue.

**Comment by K-Phoen** [comment]
You probably don't have any data in elasticsearch yet. You can use the [generator](http://logstash.net/docs/1.4.2/inputs/generator) input in Logstash to generate random data.

**Comment by willdurand** [comment]
I think @K-Phoen is right.
