### ISSUE TITLE
Include /opt/logstash/bin in default PATH

### ISSUE THREAD

**Issue by focusaurus** [willdurand/docker-elk#9]
This is a nice-to-have that the official library/logstash image has but your elk image does not. If I "docker run" this image with `/bin/bash` command for some interactive experimentation, the default root shell's `PATH` does not include `/opt/logstash/bin` so just typing `logstash` results in command not found error. In the `library/logstash` this is set up for you nicely.

**Comment by willdurand** [comment]
:+1:
